# This configuration file tells GraphQL Code Generator how
# to generate types based on our schema.
schema: "http://localhost:3000/graphql"
generates:
  # Specify where our generated types should live.
  ./libs/__generated__/graphql-types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      useIndexSignature: true
      # More on this below!
