/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * NestJS API
 * desc
 * OpenAPI spec version: 1.0
 */
export interface UpdateCustomerDto {
  readonly id?: number;
  firstname?: string;
  lastname?: string;
  phone?: string;
  email?: string;
  company?: number | null;
}

export interface Customer {
  readonly id: number;
  firstname: string;
  lastname: string;
  phone: string;
  email: string;
  company: number | null;
}

export interface CreateCustomerDto {
  readonly id: number;
  firstname: string;
  lastname: string;
  phone: string;
  email: string;
  company: number | null;
}

export interface UpdateCompanyDto {
  id?: number;
  legalname?: string;
  taxid?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  siret?: string;
  ape?: string;
  legalform?: string;
  website?: string;
  logo?: string;
  description?: string;
  industry?: string;
}

export interface Company {
  id: number;
  legalname: string;
  taxid: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  siret: string;
  ape: string;
  legalform: string;
  website: string;
  logo: string;
  description: string;
  industry: string;
}

export interface CreateCompanyDto {
  id: number;
  legalname: string;
  taxid: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  siret: string;
  ape: string;
  legalform: string;
  website: string;
  logo: string;
  description: string;
  industry: string;
}

export interface Estimate {
  id: number;
  customer: number;
  billingAddress: number;
  shippingAddress: number;
  items: EstimateFields[];
  title: string;
  description: string;
  date: Date;
  dueDate: Date;
  terms: string;
  notes: string;
  tax: number;
  globalDiscount: number;
  owner: number;
}

export interface EstimateFields {
  id: number;
  estimate: Estimate;
  title: string;
  description: string;
  quantity: number;
  unitPrice: number;
  discount: number;
  tax: number;
}

export interface UpdateEstimateDto {
  id?: number;
  customer?: number;
  billingAddress?: number;
  shippingAddress?: number;
  items?: EstimateFields[];
  title?: string;
  description?: string;
  date?: Date;
  dueDate?: Date;
  terms?: string;
  notes?: string;
  tax?: number;
  globalDiscount?: number;
  owner?: number;
}

export interface CreateEstimateDto {
  id: number;
  customer: number;
  billingAddress: number;
  shippingAddress: number;
  items: EstimateFields[];
  title: string;
  description: string;
  date: Date;
  dueDate: Date;
  terms: string;
  notes: string;
  tax: number;
  globalDiscount: number;
  owner: number;
}

export interface ChangePasswordDTO {
  oldpassword: string;
  newpassword: string;
  confirmpassword: string;
}

export interface LoginResponse {
  access_token: string;
}

export interface LoginDTO {
  email?: string;
  password?: string;
}

export interface RegisterDTO {
  email: string;
  password: string;
}

export interface DeleteResult {
  [key: string]: any;
}

export interface UpdateUserDto {
  [key: string]: any;
}

export interface User {
  id: number;
  email: string;
  password: string;
  Company: number;
  customers: string[];
}

export interface CreateUserDto {
  id: number;
  email: string;
  password: string;
  Company: number;
  customers: string[];
}
